export const ALLOWED_SEND_CHANNELS = [
  'bridge:fetch',
  'bridge:subscribe',
  'bridge:unsubscribe',
  'sandbox:load',
  'sandbox:unload',
  'pipeline:subscribe',
  'pipeline:unsubscribe',
] as const

export const ALLOWED_INVOKE_CHANNELS = [
  'config:get',
  'config:set',
  'file:read',
  'file:write',
  'file:exists',
  'file:delete',
  'project:open',
  'project:save',
  'project:create',
  'project:list-recent',
  'component:read',
  'component:write',
  'component:list',
  'component:list-all',
  'app:get-version',
  'window:set-title',
  'agent:run',
  'agent:permission-response',
  'server:search',
  'server:publish',
  'server:connect',
  'server:disconnect',
  'shell:openExternal',
  'models:fetch',
  'canvas:load',
  'canvas:add-component',
  'session:create',
  'session:save',
  'session:load',
  'session:list-for-component',
  'pipeline:list',
  'pipeline:get-data',
  'pipeline:start',
  'pipeline:stop',
  'pipeline:status',
] as const

export const ALLOWED_LISTEN_CHANNELS = [
  'bridge:fetch:resp',
  'bridge:event',
  'sandbox:load:resp',
  'sandbox:error',
  'agent:token',
  'agent:tool-call',
  'agent:tool-result',
  'agent:done',
  'agent:error',
  'agent:orchestrator:status',
  'agent:build:start',
  'agent:build:plan',
  'agent:build:partial',
  'agent:permission-request',
  'pipeline:data',
  'pipeline:status-change',
  'pipeline:error',
  'agent:build:pipeline-plan',
  'agent:action',
] as const

export type SendChannel = typeof ALLOWED_SEND_CHANNELS[number]
export type InvokeChannel = typeof ALLOWED_INVOKE_CHANNELS[number]
export type ListenChannel = typeof ALLOWED_LISTEN_CHANNELS[number]
